Add failing CI workflows for testing /aviator revise --ci

diff --git a/.github/workflows/pass_fail.yml b/.github/workflows/pass_fail.yml
--- a/.github/workflows/pass_fail.yml
+++ b/.github/workflows/pass_fail.yml
@@ -14,5 +14,5 @@ jobs:
     - uses: actions/checkout@v4
     - name: Always fail
       run: |
-        echo success
-        exit 0
+        echo "This test is intentionally failing"
+        exit 1
